### PR TITLE
fix table invisible

### PR DESCRIPTION
**Pull request by v123582**

### CODE REVIEW

**Comment by tufu9441** [comment]
我测试了一下，会影响到代码框……

**Comment by v123582** [comment]
@tufu9441 sorry, let me fix it later.

**Comment by v123582** [comment]
@tufu9441 i updated the code to avoid affecting others, like it:
Imgur

**Comment by tufu9441** [comment]
I have tried your new codes but it still affects some places, such as:

screencapture at wed nov 25 11 15 46 cst 2015

**Comment by v123582** [comment]
@tufu9441, sorry and i update again.

**Pull request merged**
