### PR TITLE
Add copyright info support

### PR DESCRIPTION
**Pull request by hiberabyss**
With this pull request, user could add copyright info after the content of blog.

Thanks!

### CODE REVIEW

**Comment by tufu9441** [comment]
Is there any demo using this feature? Maybe I should see the effect.

**Comment by hiberabyss** [comment]
@tufu9441 Here is an example blog: https://hiberabyss.github.io/2018/05/06/hexo-copyright-recommendations

**Comment by tufu9441** [comment]
Thanks for your contribution, however the codes added to the `post.pug` include much Chinese characters without translation, which may not be friendly to users in other languages, I am afraid so. Could you please perfect it?

**Comment by hiberabyss** [comment]
@tufu9441 Move Chinese characters into the language file, please check!

Thanks!

**Pull request merged**
