### PR TITLE
Use config file manage static files's dictionary,eazy to use CDN.

### PR DESCRIPTION
**Pull request by cielpy**
Maybe the code looks ugly, I'm not a Web developer, also not good at front-end development, so it's better for you to review the code careful.Best wishes. :)

### CODE REVIEW

**Comment by tufu9441** [comment]
It seems your improvements was based on an older version of the theme, so there are some conflicts. Can you update it to the newest version and then create a pull request again?

**Comment by cielpy** [comment]
oops....
image

**Comment by cielpy** [comment]
I have update the code :)

**Comment by tufu9441** [comment]
There is still something wrong in after_footer.jade: `codeblocker-resizer.js` and `smartresize.js` should be added in the last line instead of first line, besides you did not delete the old code. So the correct should be like this: 
```
if theme.fancybox
  script(type='text/javascript', src=url_for(theme.js) + '/fancybox.pack.js' + '?v=' + theme.version)
  script(type='text/javascript', src=url_for(theme.js) + '/jquery.fancybox.js' + '?v=' + theme.version)
  link(rel='stylesheet', type='text/css', href=url_for(theme.css) + '/jquery.fancybox.css' + '?v=' + theme.version)

if theme.duoshuo
  script.
    var duoshuoQuery = {short_name:'#{theme.duoshuo}'};
    (function() {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0]
            || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();

if theme.tinysou
  script.
    var option = {
      engineKey: '#{theme.tinysou}'
    };
    (function(w,d,t,u,n,s,e){
      s = d.createElement(t);
      s.src = u;
      s.async = 1;
      w[n] = function(r){
        w[n].opts = r;
      };
      e = d.getElementsByTagName(t)[0];
      e.parentNode.insertBefore(s, e);
    })(window,document,'script','//tinysou-cdn.b0.upaiyun.com/ts.js','_ts');
    _ts(option);

if theme.swiftype
  script.
    (function(w,d,t,u,n,s,e){w['SwiftypeObject']=n;w[n]=w[n]||function(){
    (w[n].q=w[n].q||[]).push(arguments);};s=d.createElement(t);
    e=d.getElementsByTagName(t)[0];s.async=1;s.src=u;e.parentNode.insertBefore(s,e);
    })(window,document,'script','//s.swiftypecdn.com/install/v2/st.js','_st');

    _st('install','#{theme.swiftype}','2.0.0');

if theme.google_analytics
  script.
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create','#{theme.google_analytics}','auto');ga('send','pageview');

if theme.baidu_analytics
  script.
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?#{theme.baidu_analytics}";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
      })();

script(type='text/javascript', src=url_for(theme.js) + '/codeblock-resizer.js' + '?v=' + theme.version)
script(type='text/javascript', src=url_for(theme.js) + '/smartresize.js' + '?v=' + theme.version)
```

**Comment by cielpy** [comment]
Wait...

**Comment by cielpy** [comment]
Maybe it's right now...

**Pull request merged**
